BIN_DIR := $(HOME)/.local/bin

# Tree-sitter grammars whose highlights.scm we vendor into engine/highlight/queries/<lang>/.
# Format: <lang>:<module-path>. Add a new language by appending one line.
QUERY_LANGS := \
	go:github.com/tree-sitter/tree-sitter-go \
	lua:github.com/tree-sitter-grammars/tree-sitter-lua \
	yaml:github.com/tree-sitter-grammars/tree-sitter-yaml

.PHONY: all build clean install uninstall test fmt vet sync-queries

all: build

build:
	cd ai && go build ./...
	cd agent && go build ./...
	cd engine && go build ./...
	cd kit && go build ./...
	cd coding && go build ./...
	mkdir -p tui/bin
	cd tui && go build -o bin/nib-code ./cmd/nib-code
	mkdir -p cmd/agent/bin
	cd cmd/agent && go build -o bin/nib-agent .

install: build
	mkdir -p $(BIN_DIR)
	ln -sf $(CURDIR)/tui/bin/nib-code $(BIN_DIR)/nib-code
	ln -sf $(CURDIR)/cmd/agent/bin/nib-agent $(BIN_DIR)/nib-agent
	@echo "Installed. Ensure $(BIN_DIR) is in PATH."

uninstall:
	rm -f $(BIN_DIR)/nib-code $(BIN_DIR)/nib-agent

test:
	cd ai && go test ./...
	cd agent && go test ./...
	cd engine && go test ./...
	cd kit && go test ./...
	cd coding && go test ./...
	cd tui && go test ./...
	cd cmd/agent && go test ./...

fmt:
	cd ai && go fmt ./...
	cd agent && go fmt ./...
	cd engine && go fmt ./...
	cd kit && go fmt ./...
	cd coding && go fmt ./...
	cd tui && go fmt ./...
	cd cmd/agent && go fmt ./...

vet:
	cd ai && go vet ./...
	cd agent && go vet ./...
	cd engine && go vet ./...
	cd kit && go vet ./...
	cd coding && go vet ./...
	cd tui && go vet ./...
	cd cmd/agent && go vet ./...

clean:
	rm -f tui/bin/*
	rm -f cmd/agent/bin/*

# Re-vendor highlights.scm for every language in QUERY_LANGS, resolving the
# exact on-disk path from each module's current pinned version. Run after
# bumping a tree-sitter grammar dependency.
sync-queries:
	@set -e; for pair in $(QUERY_LANGS); do \
		lang=$${pair%%:*}; \
		mod=$${pair#*:}; \
		dir=$$(cd engine && go list -m -f '{{.Dir}}' $$mod); \
		src=$$dir/queries/highlights.scm; \
		dst=engine/highlight/queries/$$lang/highlights.scm; \
		if [ ! -f "$$src" ]; then echo "missing: $$src" >&2; exit 1; fi; \
		mkdir -p "engine/highlight/queries/$$lang"; \
		install -m 644 "$$src" "$$dst"; \
		echo "synced $$mod@$$(cd engine && go list -m -f '{{.Version}}' $$mod) -> $$dst"; \
	done
